control.cmd:
  assemble: control.asm
  depends:
  - games/marooned/control.asm
  - include/include/doscalls.asm
marooned.cmd:
  assemble: marooned.asm
  depends:
  - games/marooned/marooned.asm
  - include/include/doscalls.asm
