;COMMANDS/EDT: EXTENDS THE RANGE OF DOS COMMANDS.
;ASSUMES SYSLOAD TO BE IN MEMORY AND RUNNING.
; Assembled OK 30-Mar-85.

*GET	DOSCALLS

	ORG	0D300H
START	LD	HL,0D400H
	LD	(0D877H),HL
	LD	(0DAB8H),HL
	LD	HL,0D2FFH
	LD	(4049H),HL
	LD	HL,MESS
	CALL	MESS_DO
	JP	402DH
MESS	DEFM	'NOW TAKING COMMAND TABLE FROM D400H'
	DEFB	03H
	END	START
