listalc.cmd:
  assemble: listalc.asm
  depends:
  - include/include/listalc.asm
  skip: FIXME is not top-level
reada.cmd:
  assemble: reada.asm
  depends:
  - include/include/reada.asm
  skip: FIXME no end statement - cannot be top level
