gettok.cmd:
  link: gettok
  depends:
  - gettok.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
gettok.rel:
  sdcc: gettok.c
  depends:
  - gettok.c
toknum.cmd:
  link: toknum
  depends:
  - toknum.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
toknum.rel:
  sdcc: toknum.c
  depends:
  - toknum.c
