LIB_SDCC=../../library/sdcc
include $(LIB_SDCC)/include.mk

EXTRALIBS=../../library/sdcc/basicio.lib ../../library/sdcc/newdos80.lib

all: gettok.cmd toknum.cmd

gettok.cmd: $(EXTRALIBS)

.PHONY: all
