;kill: Kill a file off disk.
;
*GET	DOSCALLS.HDR
*GET	EXTERNAL.HDR
*GET	ASCII.HDR
;
	ORG	PROG_START
	DEFW	BASE
	DEFW	THIS_PROG_END
	DEFW	TERMINATE
	DEFW	TERMINATE
;End of program load info.
;
	COM	'<Kill 1.0  20-Apr-86>'
	ORG	BASE+100H
START	LD	SP,START
;
	LD	A,(PRIV_1)
	BIT	IS_SYSOP,A
	JR	NZ,KILL_ANY
;
;Kill tempfile only.
	LD	HL,M_TEMPFILE
	LD	DE,($STDOUT)
	CALL	FPUTS
;
	LD	HL,TEMPFILE
KILL_ANY
	LD	DE,FCB_KILL
	CALL	EXTRACT
	LD	HL,0
	LD	B,0
	CALL	DOS_OPEN_EX
	JP	NZ,NONEX
	CALL	DOS_KILL
	JP	NZ,NOKILL
	XOR	A
	JP	TERMINATE
;
NONEX	LD	HL,M_NONEX
	LD	DE,($STDOUT)
	CALL	FPUTS
	LD	A,128
	JP	TERMINATE
;
NOKILL	LD	HL,M_NOKILL
	LD	DE,($STDOUT)
	CALL	FPUTS
	LD	A,129
	JP	TERMINATE
;
*GET	ROUTINES
;
M_NONEX	DEFM	'Kill: File not in directory',CR,0
M_NOKILL
	DEFM	'Kill: Insufficient access to kill',CR,0
M_TEMPFILE
	DEFM	'Kill: Killing file called TEMPFILE',CR,0
TEMPFILE
	DEFM	'tempfile',CR,0
FCB_KILL	DEFS	32
;
THIS_PROG_END	EQU	$
;
	END	START
