libc.lib:
  library: libc.lib
  depends:
  - atoi.rel
  - fileio.rel
  - putchar.rel
  - sbrk.rel
  - stricmp.rel
atoi.rel:
  sdcc: atoi.c
  depends:
  - atoi.c
fileio.rel:
  sdcc: fileio.c
  copy:
  - library/newdos80/doscalls.h
  depends:
  - fileio.c
putchar.rel:
  sdcc: putchar.c
  depends:
  - putchar.c
sbrk.rel:
  sdcc: sbrk.c
  depends:
  - sbrk.c
stricmp.rel:
  sdcc: stricmp.c
  depends:
  - stricmp.c
