;msghdr.hdr: format of MSGHDR.ZMS file.
;Last updated 19-Aug-88
;
HDR_LEN		EQU	16
;
HDR_REC
;
HDR_FLAG	DEFB	0
HDR_LINES	DEFB	0
HDR_RBA		DEFB	0,0,0
HDR_DATE	DEFB	0,0,0
HDR_SNDR	DEFW	0
HDR_RCVR	DEFW	0
HDR_TOPIC	DEFB	0
HDR_TIME	DEFB	0,0,0
;
;Format of HDR_FLAG
FM_KILLED	EQU	0
FM_PRIVATE	EQU	1
FM_IMPORT	EQU	2
FM_RUDE		EQU	3
FM_NETMSG	EQU	4
FM_NETSENT	EQU	5
FM_FIDONET	EQU	6
FM_ACSNET	EQU	7
;
;End of msghdr.
