;stats: Format of STATS.ZMS file
;
STATS_REC
ST_TOT_CALLS	DEFW	0
ST_LOGGED_IN	DEFW	0
ST_NO_LOGIN	DEFW	0
ST_NO_CARRIER	DEFW	0
ST_NON_MEMBER	DEFW	0
ST_DISCON	DEFW	0
ST_PKTS_RCVD	DEFW	0
ST_PKTS_SENT	DEFW	0
;
;End of stats file definitions.
