cwiz.cmd:
  link: cwiz
  depends:
  - cwiz.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
cwiz.rel:
  sdcc: cwiz.c
  depends:
  - cwiz.c
wisdom.cmd:
  link: wisdom
  depends:
  - wisdom.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
wisdom.rel:
  sdcc: wisdom.c
  depends:
  - wisdom.c
