ftalk.cmd:
  assemble: ftalk.asm
  depends:
  - zeta-bbs/comm/ftalk/ftalk.asm
  - include/include/ascii.asm
  - include/include/ci_cmp.asm
  - include/include/doscalls.asm
  - include/include/external.asm
  - zeta-bbs/include/fidonet.asm
  - zeta-bbs/include/routines.asm
  - zeta-bbs/include/rs232.asm
  - zeta-bbs/include/sec10.asm
  - zeta-bbs/include/stats.asm
  - zeta-bbs/include/userfile.asm
ftalk2.cmd:
  assemble: ftalk2.asm
  depends:
  - zeta-bbs/comm/ftalk/ftalk2.asm
  - include/include/ascii.asm
  - include/include/ci_cmp.asm
  - include/include/doscalls.asm
  - include/include/external.asm
  - zeta-bbs/include/fidonet.asm
  - zeta-bbs/include/routines.asm
  - zeta-bbs/include/rs232.asm
  - zeta-bbs/include/sec10.asm
  - zeta-bbs/include/sputnum.asm
  - zeta-bbs/include/stats.asm
  - zeta-bbs/include/userfile.asm
