;libcz: Standard I-O library for Small-C, Zeta
;
;
EOF	EQU	-1
NULL	EQU	0
;_EOF	EQU	-1
_NULL	EQU	0
;
;File descriptor array
;
MAX_FILES	EQU	20
FD_LEN		EQU	3
KBD_DCB		EQU	DCB_2I
VDU_DCB		EQU	DCB_2O
PTR_DCB		EQU	4025H
;
FD_ARRAY	DC	MAX_FILES*FD_LEN,0
;
;Contents:
FD_FLAG		EQU	0
FD_FCBPTR	EQU	1
;
IS_USED	EQU	0	;bits of fd_flag
IS_TERM	EQU	1	;its a terminal or dcb.
IS_CHAR	EQU	1	;Is a character device
ECHO	EQU	2
CBREAK	EQU	3
;
STDIN	EQU	0*FD_LEN+FD_ARRAY
STDOUT	EQU	1*FD_LEN+FD_ARRAY
STDERR	EQU	2*FD_LEN+FD_ARRAY
_STDIN	EQU	STDIN
_STDOUT	EQU	STDOUT
_STDERR	EQU	STDERR
BUFSIZ	EQU	256
