usrclean.cmd:
  assemble: usrclean.asm
  depends:
  - include/include/ascii.asm
  - include/include/doscalls.asm
  - include/include/external.asm
  - zeta-bbs/include/fputs.asm
  - zeta-bbs/include/multiply.asm
  - zeta-bbs/include/rs232.asm
  - zeta-bbs/include/userfile.asm
  - zeta-bbs/maintain/usrclean/usrclean.asm
