duplic20.cmd:
  assemble: duplic20.asm
  depends:
  - duplic20.asm
  - include/include/doscalls.asm
duplic21.cmd:
  assemble: duplic21.asm
  depends:
  - duplic21.asm
  - include/include/doscalls.asm
  - include/include/fd1771.asm
  - include/include/hex.asm
duplicat.cmd:
  assemble: duplicat.asm
  depends:
  - duplicat.asm
  - include/include/doscalls.asm
