;const.asm	h/const.h
;
TRUE		EQU	1
FALSE		EQU	0
;
BLOCK_SIZE	EQU	1024	;Consider change to 512
SUPER_USER	EQU	0
;
MAJOR		EQU	4	;Higher 4 bits of byte
MINOR		EQU	0
;
NR_TASKS	EQU	8
NR_PROCS	EQU	16
NR_SEGS		EQU	3	;?
T		EQU	0
D		EQU	1
S		EQU	2
;
CLICK_SIZE	EQU	1024
CLICK_SHIFT	EQU	10
;
MM_PROC_NR	EQU	0
FS_PROC_NR	EQU	1
INIT_PROC_NR	EQU	2
LOW_USER	EQU	2
;
;	Miscellaneous
;
BYTE		EQU	255
TO_USER		EQU	0
FROM_USER	EQU	1
READING		EQU	0
WRITING		EQU	1
ABS		EQU	-999
;
WORD_SIZE	EQU	2
NIL_PTR		EQU	0
;
NO_NUM		EQU	8000H
MAX_PATH	EQU	128
SIG_PUSH_BYTES	EQU	8
MAX_ISTACK_BYT	EQU	1024	;?
;
;	Device numbers of root (ram) & boot (fd0) devices
ROOT_DEV	EQU	1>>MAJOR
BOOT_DEV	EQU	2>>MAJOR
;
;	Flag bits for i_mode in the inode
I_TYPE		EQU	0F000H
I_REGULAR	EQU	8000H
I_BLOCK_SPECIA	EQU	6000H
I_DIRECTORY	EQU	4000H
I_CHAR_SPECIAL	EQU	2000H
I_SET_UID_BIT	EQU	0800H
I_SET_GIT_BIT	EQU	0400H
ALL_MODES	EQU	0DFFH
RWX_MODES	EQU	01FFH
R_BIT		EQU	4
W_BIT		EQU	2
X_BIT		EQU	1
I_NOT_ALLOC	EQU	0
;
