C234567890
      SUBROUTINE CRSUB
      RETURN
      END
      SUBROUTINE DELSUB
      RETURN
      END
      SUBROUTINE INSLK
      RETURN
      END
      SUBROUTINE DELLK
      RETURN
      END
      SUBROUTINE EOF6
      RETURN
      END
