;fs2: Patch to FS1 (normal) for joystick.
; Assembled OK 30-Mar-85.
	ORG	877AH
	JP	KEYBOARD
	ORG	0C000H
KEYBOARD	LD	A,(3820H)
	RLA
	JP	C,4A45H	;BRAKES
	RLA
	JP	C,4A20H	;INCREASE THROTTLE
	RLA
	RLA
	JP	C,4A2CH	;DECREASE THROTTLE
	LD	A,(3801H)
	AND	2
	JP	NZ,4A38H
	LD	A,(3804H)
	AND	2
	JP	NZ,4A40H
	LD	A,(3840H)
	LD	H,A
	AND	60H
	JR	NZ,BYPASS
	XOR	A
	LD	(44C3H),A
BYPASS	LD	A,H
	RLA
	JP	C,551EH	;FIRE MACHINE GUN
	RLA
	PUSH	AF
	CALL	C,4A5DH	;RIGHT RUDDER & AILERONS
	POP	AF
	RLA
	PUSH	AF
	CALL	C,4AADH	;LEFT RUDDER & AILERONS
	POP	AF
	RLA
	PUSH	AF
	CALL	C,4ACDH	;ELEVATORS UP
	POP	AF
	RLA
	CALL	C,4AE1H	;ELEVATORS DOWN
	XOR	A	;CLEAR FOR KBD ROUTINE.
	JP	4A89H	;NORMAL KEYBOARD ROUTINE.
	END	0BD10H
