boot-sector.cmd:
  link: boot-sector
  depends:
  - boot-sector.rel
  - library/basicio/basicio.lib
  - library/fd1771/fd1771.lib
  - library/newdos80/newdos80.lib
boot-sector.rel:
  sdcc: boot-sector.c
  depends:
  - boot-sector.c
