cdirect.cmd:
  link: cdirect
  depends:
  - cdirect.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
cdirect.rel:
  sdcc: cdirect.c
  depends:
  - cdirect.c
direct.cmd:
  assemble: direct.asm
  depends:
  - direct.asm
  - include/include/doscalls.asm
