;pktass: Assemble echomail/news messages into outgoing packets.
;This new pktass does not handle netmail at all.
;
*GET	DOSCALLS
*GET	EXTERNAL
*GET	ASCII
*GET	FIDONET
;
ALLNET		EQU	0	;1=Send out msgs with fm_netmsg bit ZERO
ECHO_GENERAL	EQU	0	;1=General is an echomail topic TO_ZETA.
;
	ORG	PROG_START
	DEFW	BASE
	DEFW	THIS_PROG_END
	DEFW	0
	DEFW	0
;End of program load info
;
	COM	'<Pktass 2.1  19-Jun-89>'
	ORG	BASE+100H
;
START	LD	SP,START
;
	LD	A,(PRIV_1)
	BIT	IS_SYSOP,A
	LD	A,0
	JP	Z,TERMINATE
;
*GET	PKTASS1
*GET	BB7
;
*GET	ROUTINES
*GET	CI_CMP
;
;Data section...........................................
;
TXT_FCB	DEFM	'msgtxt.zms',CR
		DC	32-11,0
TOP_FCB	DEFM	'msgtop.zms',CR
		DC	32-11,0
HDR_FCB	DEFM	'msghdr.zms',CR
		DC	32-11,0
NETN_FCB	DEFM	'netn.zms',CR
		DC	32-9,0
NETL_FCB	DEFM	'netl.zms',CR
		DC	32-9,0
PKT_FCB		DC	32,0
;
MSGTXT_BUF	EQU	_BLOCK
MSGTOP_BUF	DEFS	256
MSGHDR_BUF	DEFS	256
NETN_BUF	DEFS	256
NETL_BUF	DEFS	256
PKT_BUF		DEFS	256
;
EM	DEFW	0
MSGBUF	DEFW	0
NLPTR	DEFW	0
LTPTR	DEFW	0
EMPTR	DEFW	0	;echomail table pointer.
MSGNO	DEFW	-1
;
LINK	DEFS	75	;room for 25 links
NODE	DEFS	300	;room for 50 nodes
;
NODE_SHORT	DEFW	0
NODE_FIDONODE	DEFW	0
NODE_LINK	DEFW	0
;
LINK_NAME	DEFW	0
LINK_FIDONODE	DEFW	0
LINK_FILENAME	DEFW	0
;
ROUTE_NET_NUM	DEFW	0
ROUTE_NODE_NUM	DEFW	0
TO_NET_NUM	DEFW	0
TO_NODE_NUM	DEFW	0
;
ORIG_NAME	DEFS	64	;"nick andrew@zeta"
DEST_NAME	DEFS	64	;"gary stern@realtors"
DATE_LEFT	DEFS	64	;"23 Oct 86  22:01:44"
SUBJECT		DEFS	73	;"Blah"
PRIM_LINK	DEFS	64
CURRENT_FILE	DEFS	32
CURRENT_FILEA	DEFS	32
FILE_APPEND	DEFM	'/poof:2',0
;
*GET	MSGHDR
;
NET_ADDRESS	DEFW	0	;Addr of @"prophet"
LINK_TOUSE	DEFW	0
ROUTE_ADDRESS	DEFW	0
ROUTE_FILENAME	DEFM	'xxxxxxxx.OUT/POOF:2',0
;
S_AREA	DEFM	'AREA:',0
;
M_OPENING
	DEFM	'Opening packet: ',0
M_CORRUPT
	DEFM	'Something is corrupt!',CR,0
M_NOFF	DEFM	'No FF byte at start of message',CR,0
M_NOTNET
	DEFM	'NETmsg bit set but no "@" in dest',CR,0
M_UNKNLINK
	DEFM	'linkname in NETN.ZMS unknown',CR,0
M_BADADD
	DEFM	'Bad network address at ',0
M_FROM	DEFM	'# From ',0
M_TO	DEFM	'  to  ',0
M_CR	DEFM	CR,0
M_ONLINK
	DEFM	'Sending on link: ',0
;
ACSLINK	DEFM	'acsnet',0
ON_ACS	DEFB	0
;
ADDRESS	DEFM	'To: '
ADDRESSL	DEFB	0
	DC	64,0
;
;
F_ECHO	DEFB	0
ECHO_AREA	DEFW	0	;addr of AREA: line.
ECHO_ORIGIN	DEFW	0	;addr of ORIGIN lines
ECHO_COORD	DEFW	0	;addr of net,node ints
;
*GET	MSGTOP
;
;Echomail control information....
ECHOMAIL
;
	IF	ECHO_GENERAL
	DEFB	00000000B	;GENERAL
	DEFB	AREA_0
	DEFB	COORD_2
	DEFB	ORIGIN_2
	ENDIF
;
	DEFB	00100100B	;AUST_XENIX (24h)
	DEFW	AREA_24
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00101000B	;Intensive-C (28h)
	DEFW	AREA_28
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00101100B	;Mainframe
	DEFW	AREA_2C
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00110000B	;AUST_C_HERE
	DEFW	AREA_30
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00110100B	;AUST_MEDICAL
	DEFW	AREA_34
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00111001B	;BBS_NEWS
	DEFW	AREA_39
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00111010B	;BBS_USER
	DEFW	AREA_3A
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	00111011B	;BBS_SYSOP
	DEFW	AREA_3B
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	01000100B	;UNET_MINIX
	DEFW	AREA_44
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	01101001B	;ZONE3_SYSOP
	DEFW	AREA_69
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	01101010B	;RG54_SYSOP
	DEFW	AREA_6A
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	01101011B	;NET713_SYSOP
	DEFW	AREA_6B
	DEFW	COORD_1
	DEFW	ORIGIN_1
;
	DEFB	10100100B	;COMP.SYS.TRANSPUTER
	DEFW	AREA_A4
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	10101000B	;AUS.WANTED
	DEFW	AREA_A8
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	10101100B	;COMP.UNIX.XENIX
	DEFW	AREA_AC
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11000100B	;AUS.JOKES & REC.HUMOR.FUNNY
	DEFW	AREA_C4
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11001000B	;AUS.SF
	DEFW	AREA_C8
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11001100B	;AUS.GENERAL
	DEFW	AREA_CC
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11010000B	;AUS.COMPUTERS.AMIGA
	DEFW	AREA_D0
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11010100B	;AUS.FORSALE
	DEFW	AREA_D4
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11011000B	;AUS.JOBS
	DEFW	AREA_D8
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	11011100B	;AUS.AI
	DEFW	AREA_DC
	DEFW	COORD_2
	DEFW	ORIGIN_2
;
	DEFB	0
	DEFW	0,0,0		;end of table.
;
COORD_1
	DEFW	713,606		;To Prophet
;
COORD_2
	DEFW	713,603		;To ACSgate
;
AREA_0	DEFM	'TO_ZETA',CR,LF,0
AREA_24	DEFM	'AUST_XENIX',CR,LF,0
AREA_28	DEFM	'I_C_U',CR,LF,0
AREA_2C	DEFM	'MAINFRAME',CR,LF,0
AREA_30	DEFM	'AUST_C_HERE',CR,LF,0
AREA_34	DEFM	'AUST_MEDICAL',CR,LF,0
AREA_39	DEFM	'BBS_NEWS',CR,LF,0
AREA_3A	DEFM	'BBS_USER',CR,LF,0
AREA_3B	DEFM	'BBS_SYSOP',CR,LF,0
AREA_44	DEFM	'COMP.OS.MINIX',CR,LF,0
AREA_69	DEFM	'ZONE3_SYSOP',CR,LF,0
AREA_6A	DEFM	'RG54_SYSOP',CR,LF,0
AREA_6B	DEFM	'NET713_SYSOP',CR,LF,0
AREA_A4	DEFM	'COMP.SYS.TRANSPUTER',CR,LF,0
AREA_A8	DEFM	'AUS.WANTED',CR,LF,0
AREA_AC	DEFM	'COMP.UNIX.XENIX',CR,LF,0
AREA_C4	DEFM	'AUS.JOKES',CR,LF,0
AREA_C8	DEFM	'AUS.SF',CR,LF,0
AREA_CC	DEFM	'AUS.GENERAL',CR,LF,0
AREA_D0	DEFM	'AUS.COMPUTERS.AMIGA',CR,LF,0
AREA_D4	DEFM	'AUS.FORSALE',CR,LF,0
AREA_D8	DEFM	'AUS.JOBS',CR,LF,0
AREA_DC	DEFM	'AUS.AI',CR,LF,0
;
ORIGIN_1
	DEFM	'--- Zeta',CR,LF
	DEFM	' * Origin: Zeta: Unix, Minix, Xenix support!'
	DEFM	' (02) 627-4177 (3:713/602)',CR,LF	; --ZETA_NUM--
	DEFM	'SEEN-BY: 713/602 713/606',CR,LF	; --ZETA_NUM--
	DEFM	CR,LF,0
;
ORIGIN_2
	DEFM	'--- Zeta',CR,LF
	DEFM	' * Origin: Zeta: Unix, Minix, Xenix support'
	DEFM	' (02) 627-4177 (3:713/602)',CR,LF	; --ZETA_NUM--
	DEFM	'SEEN-BY: 713/602 713/603',CR,LF	; --ZETA_NUM--
	DEFM	CR,LF,0
;
BIG_BUFF	DEFS	1024
;
THIS_PROG_END	EQU	$
;
	END	START
