decode.cmd:
  assemble: decode.asm
  depends:
  - lang/decode/decode.asm
  - include/include/doscalls.asm
decode1.cmd:
  assemble: decode1.asm
  depends:
  - lang/decode/decode1.asm
decodem.cmd:
  assemble: decodem.asm
  depends:
  - lang/decode/decodem.asm
