;xmodem: Extended Xmodem CRC file transfer.
;
*GET	DOSCALLS
*GET	EXTERNAL
*GET	ASCII
;
	ORG	PROG_START
	DEFW	BASE
	DEFW	THIS_PROG_END
	DEFW	0
	DEFW	TERMINATE
;End of program load info.
;
;UART equates...
RDDATA	EQU	0F8H
WRDATA	EQU	0F8H
RDSTAT	EQU	0F9H
WRSTAT	EQU	0F9H
DAV	EQU	1
CTS	EQU	0
;
;XMODEM protocol type equates...
SOH	EQU	01H
EOT	EQU	04H
ENQ	EQU	05H
ACK	EQU	06H
NAK	EQU	15H
SYN	EQU	16H	;Telink block header
CAN	EQU	18H
CRCNAK	EQU	'C'	;Initial NAK ala CRC mode
SUB	EQU	1AH	;Control char for modem7
;
;Constants
BLOCKSIZE	EQU	128
MAX_NAKS	EQU	0AH
MAX_BLOCKS	EQU	18H	;Was 14H.
;
	COM	'<Xmodem 1.11  12-Jan-88>'
	ORG	BASE+100H
;
*GET	XMODEM1
*GET	XMODEM2
;
BIG_BUFF
	NOP
;
	DEFS	MAX_BLOCKS*128
THIS_PROG_END	EQU	$
;
	END	START
