LIB_SDCC=../../library/sdcc
include $(LIB_SDCC)/include.mk

EXTRALIBDIR=
EXTRALIBS=../../library/sdcc/basicio.lib ../../library/sdcc/newdos80.lib

all: fileio.cmd

fileio.cmd: $(EXTRALIBS)

.PHONY: all
