cat.cmd:
  assemble: cat.asm
  depends:
  - zeta-bbs/utilities/cat/cat.asm
  - include/include/ascii.asm
  - include/include/doscalls.asm
  - include/include/external.asm
  - zeta-bbs/include/extract.asm
  - zeta-bbs/include/mess_0.asm
  - zeta-bbs/include/rs232.asm
  - zeta-bbs/include/std_out.asm
  - zeta-bbs/include/userfile.asm
