compiler.rel:
  sdcc: compiler.c
  depends:
  - compiler.c
  - compiler.h
  - errors.h
  - goals.h
  - opcodes.h
  - la.h
  - lls.h
errors.rel:
  sdcc: errors.c
  depends:
  - errors.c
  - errors.h
  - lls.h
interp.rel:
  sdcc: interp.c
  depends:
  - compiler.h
  - interp.c
  - interp.h
  - la.h
  - opcodes.h
la.rel:
  sdcc: la.c
  depends:
  - errors.h
  - la.c
  - la.h
  - lls.h
latest.cmd:
  link: latest
  depends:
  - errors.rel
  - latest.rel
  - lls.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
latest.rel:
  sdcc: latest.c
  depends:
  - errors.h
  - latest.c
  - la.h
  - lls.h
lls.rel:
  sdcc: lls.c
  depends:
  - errors.h
  - lls.c
  - lls.h
llstest.cmd:
  link: llstest
  depends:
  - errors.rel
  - lls.rel
  - llstest.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
llstest.rel:
  sdcc: llstest.c
  depends:
  - llstest.c
  - lls.h
main.cmd:
  link: main
  depends:
  - compiler.rel
  - errors.rel
  - interp.rel
  - la.rel
  - lls.rel
  - main.rel
  - library/basicio/basicio.lib
  - library/newdos80/newdos80.lib
  - library/rom/rom.lib
  skip: fscanf() is required but not yet written
main.rel:
  sdcc: main.c
  depends:
  - compiler.h
  - interp.h
  - la.h
  - lls.h
  - main.c
  - main.h
