;Filea/asm
;
	IFDEF	SHOWA
*LIST	ON
	ELSE
*LIST	OFF
	ENDIF
;
;	TITLE	Archive File Extractor for Trs-80
IDENT	MACRO
	DB	'UNARC  1.2 24-Jun-86 for Trs-80 23-Jun-87'
	ENDM
; (Remember to update version/date here and maintain history log below)
COPR	MACRO
	DB	'Copyright (C) 1986 by Robert A. Freed.  All Rights Reserved.'
	ENDM
;
;NOTICE:  This program is the copyrighted property of its author -- it 
;is NOT in the public domain.  HOWEVER...  Free use, distribution, and 
;modification of this program is permitted (and encouraged), subject to 
;the following conditions:
;(1)  Such use or distribution must be for non-profit purposes only.
;(2)  The author's copyright notice may not be altered or removed.
;(3)  Modifications to this program may not be distributed without
;     notification of and approval by the author.
;No fee is requested or expected for the use and distribution of this 
;program subject to the above conditions.  The author reserves the right 
;to modify these conditions for any future revisions of this program.  
;Questions, comments, suggestions, commercial inquiries, and bug reports 
;or fixes are welcomed by the author:
;		Bob Freed
;		62 Miller Rd.
;		Newton Centre, MA  02159
;		Telephone (617) 332-3533
;
;	PAGE
;	SUBTTL	Modification History
;1.2	24 Jun 86  (RAF)
;Modified to allow assembly of a version which will execute on 8080/8085 
;CPU's.  (We resisted this initially but have been made to realize that 
;this is necessary to achieve true acceptance of UNARC by the full CP/M 
;user community.  Non-Z80 users, particularly RCPM sysops, still exert 
;considerable influence in the world of public domain software.  This, 
;we believe, is out of proportion to their numbers, since almost all 
;CP/M systems sold in the last five years are Z80-based.  Nevertheless, 
;we've accommodated the needs of these users by extensive use of macros 
;which serve to emulate Z80 instructions on non-Z80 machines.)  However, 
;no attempt has been made to optimize for either size or speed in the 
;non-Z80 version (which is 1K larger and 50% or more slower than its 
;Z80-only counterpart).
;Also:
;- Implements a "wheel" byte to simplify use and installation on RCPM's.
;- Lines up file types in directory listing.
;- Permits processing of "self-unpacking" archives such as the MS-DOS
;  ARC512.COM file (anticipates a future scheme for distributing UNARC).
;- Attempts to recover from bad archive headers by skipping extra bytes.
;- Eliminates archaic "T:" syntax completely for file typeout.
;1.1	24 May 86  (RAF)
;Minor change to allow file typeout without the "T:" syntax (which 
;didn't work with almost ANY CCP replacement)...  File will be typed if 
;it:  (1) has no disk drive name, (2) is a single (UNambiguous) file, 
;and (3) is not an excluded filetype.  (Else, file will simply be listed 
;with no error message.)  This change was suggested by Irv Hoff's mod to 
;UNARC10, which he called ADIR.  (Previous "T:" method can still be 
;enabled, but it is now undocumented since we will probably drop it 
;altogether in future.)
;Also shortened on-line help message, so that COM file size is now 
;reduced to 4K.  (For RCPM systems, if HODRV = 0 and/or TYFLG = 0, the 
;help information relating to disk extraction and/or file typeout, 
;respectively, is automatically removed.)
;1.0	03 May 86  (RAF)
;First public release.  Supports file formats generated by all versions 
;of MS-DOS ARC through (at least) version 5.12 dated February 7, 1986.
;\
;	PAGE
;
;0.0	01 Mar 86  (RAF)
;I undertook writing this program to satisfy my curiosity about software 
;developments in the MS-DOS/PC-DOS world.  The ARC "freeware" program 
;(copyright by System Enhancement Associates) has been around for over a 
;year now and has achieved enormous popularity in the 16-bit community.  
;Unfortunately, the lack of a compatible equivalent for CP/M systems 
;renders a large amount of public domain software inaccessible to 8-bit 
;users such as myself.  (Note that 16-bit software can indeed be usable 
;on 8-bit systems, e.g. Pascal and C language programs.)  Also, an 
;increasing number of RCPM systems are catering to both 8-bit and 16-bit 
;users, and it is my hope that UNARC may find a welcome home on such 
;systems.
;Note that I was not (initially) a fan of the sequential .ARC file 
;format, which is less flexible and slower to process (though certainly 
;more compact) than the random-access format which Novosielski .LBR 
;libraries have provided for years.  Therefore, I stopped short of 
;producing a complete ARC program equivalent which includes creation of 
;.ARC files.  The LZW "crunching" algorithm is impressive though (see my 
;editorial comments preceeding the UCR routine), and I now believe there 
;is a place for .ARC files in the CP/M world (particularly on RCPM's, 
;where the name of the game is reducing upload/download time).  But 
;that's the domain of another program (i.e. my next project: NARC).
;					- Bob Freed
;Credits:
;Primary credit is due to System Enhancement Associates' ARC author 
;Thom Henderson for his fine utility program (even if it's not for 
;CP/M).  Of course without ARC, UNARC would have no reason to exist.  
;But special thanks are due SEA for making publicly available the C 
;language source code, without which we could never have begun.  For 
;the record, their address is:
;	System Enhancement Associates
;	21 New Street
;	Wayne, NJ  07470
;In addition to numerous others credited in the ARC documentation, we 
;would be remiss not to mention Richard Greenlaw (for his implementation 
;of Huffman coding for squeezed files) and Terry A. Welch (for the LZW 
;compression method for crunched files).
;\
;	PAGE
;
NO	EQU	0
YES	EQU	.NOT.NO
	PAGE
LINLEN	EQU	80		;to 64?
