mail.cmd:
  assemble: mail.asm
  depends:
  - include/include/ascii.asm
  - include/include/ci_cmp.asm
  - include/include/doscalls.asm
  - mail.asm
  - zeta-bbs/include/$month_name.asm
  - zeta-bbs/include/$two_digit.asm
  - zeta-bbs/include/ci_hash.asm
  - zeta-bbs/include/common_search.asm
  - zeta-bbs/include/cphlde.asm
  - zeta-bbs/include/dmy_ascii.asm
  - zeta-bbs/include/external.asm
  - zeta-bbs/include/getdate.asm
  - zeta-bbs/include/get_number.asm
  - zeta-bbs/include/gettime.asm
  - zeta-bbs/include/hms_ascii.asm
  - zeta-bbs/include/linein.asm
  - zeta-bbs/include/mess_0.asm
  - zeta-bbs/include/mess_nocr.asm
  - zeta-bbs/include/morepipe.asm
  - zeta-bbs/include/multiply.asm
  - zeta-bbs/include/print_numb.asm
  - zeta-bbs/include/print_numb_dev.asm
  - zeta-bbs/include/strcmp_ci.asm
  - zeta-bbs/include/strcpy.asm
  - zeta-bbs/include/strlen.asm
  - zeta-bbs/include/userfile.asm
  - zeta-bbs/include/user_search.asm
  - zeta-bbs/treeboard/mail/mail1.asm
  - zeta-bbs/treeboard/mail/mail2.asm
  - zeta-bbs/treeboard/mail/mail3.asm
  - zeta-bbs/treeboard/mail/mail4.asm
  - zeta-bbs/treeboard/mail/mail5.asm
  - zeta-bbs/treeboard/mail/mail6.asm
  - zeta-bbs/treeboard/mail/mail7.asm
  - zeta-bbs/treeboard/mail/maildata.asm
