addlf.cmd:
  assemble: addlf.asm
  depends:
  - zeta-bbs/utilities/addlf/addlf.asm
  - include/include/ascii.asm
  - include/include/doscalls.asm
  - include/include/external.asm
  - zeta-bbs/include/extract.asm
  - zeta-bbs/include/mess_0.asm
  - zeta-bbs/include/rs232.asm
  - zeta-bbs/include/userfile.asm
addlfc.asm:
  sdcc: addlfc.c
  depends:
  - zeta-bbs/utilities/addlf/addlfc.c
