addlf.cmd:
  assemble: addlf.asm
  depends:
  - addlf.asm
  - include/include/ascii.asm
  - include/include/doscalls.asm
  - zeta-bbs/include/external.asm
  - zeta-bbs/include/extract.asm
  - zeta-bbs/include/mess_0.asm
addlf1.cmd:
  depends:
  - addlf1.rel
  - library/basicio/basicio.lib
  - library/libc/libc.lib
  - library/newdos80/newdos80.lib
  link: addlf1
addlf1.rel:
  depends:
  - zeta-bbs/utilities/addlf/addlf1.c
  sdcc: addlf1.c
addlfc.cmd:
  depends:
  - addlfc.rel
  - library/basicio/basicio.lib
  - library/libc/libc.lib
  - library/newdos80/newdos80.lib
  link: addlfc
addlfc.rel:
  depends:
  - zeta-bbs/utilities/addlf/addlfc.c
  sdcc: addlfc.c
