copygame.cmd:
  link: copygame
  depends:
  - copygame.rel
  - library/basicio/basicio.lib
  - library/fd1771/fd1771.lib
  - library/newdos80/newdos80.lib
copygame.rel:
  sdcc: copygame.c
  depends:
  - copygame.c
