boot10.cmd:
  assemble: boot10.asm
  depends:
  - include/include/doscalls.asm
  - boot10.asm
boot11.cmd:
  assemble: boot11.asm
  depends:
  - include/include/doscalls.asm
  - boot11.asm
advboot.cmd:
  assemble: advboot.asm
  depends:
  - include/include/doscalls.asm
  - advboot.asm
advboot2.cmd:
  assemble: advboot2.asm
  depends:
  - include/include/doscalls.asm
  - advboot2.asm
